### ISSUE TITLE
Reports with null end dates

### ISSUE THREAD

**Issue by jsmit106** [cst316/spring16project-Ada#3]
Reports are failing unit tests when there is a task that contains no end date.

**Comment by sjscott9** [comment]
[182d490](https://github.com/cst316/spring16project-Ada/commit/182d490d00c4ef139fefc34fe3018f88c76f48a5)

**Comment by jsmit106** [comment]
This is for reports, not task templates.

**Comment by jsmit106** [comment]
The root of the problem is an issue where TaskImpl.getEndDate() is not always returning the correct value.

**Comment by jsmit106** [comment]
Turns out the method CalendarDate.before(CalendarDate date) is creating two Calendar instances. However, everynow and then one of those instances will be created a millisecond later. This was causing two Calendar dates that lie on the same day to show one as before the other. I updated the method to create the dates in the opposite order to remedy this occasional error.

**Comment by jsmit106** [comment]
This issue has been fixed and approved per https://tree.taiga.io/project/cst316asu-spring16project-ada/task/53 will be included with the next pull from Bug Fixes.
